EXP_NAME: "LensBot Auto Lens Design"
seed: null

# optical targets
foclen: 50.0
fov: 40.0
fnum: 2.8
bfl: 18.0
thickness: 80.0
surf_list:
  - ["Spheric", "Spheric"]
  - ["Spheric", "Spheric"]
  - ["Aperture"]
  - ["Spheric", "Aspheric"]
  - ["Spheric", "Aspheric"]
lrs: [1e-3, 1e-4, 1e-2, 1e-4]

# optimization-time controls
iterations: 30
spp: 128
test_per_iter: 5
